config/routes.rb
Rails.application.routes.draw do
  get 'pages/terms'

  get 'pages/about'

  get 'welcome/index'

  root to: "documents#index"
  resources :bullet_points, except: [:show]
  resources :document_types, except: [:show]
  resources :documents, shallow: true do
    resources :reviews, except: [:show, :index]
    get :find, on: :collection
  end
  resources :users
  resources :requests, except: [:show, :edit, :update]

  get '/login', to: 'users#login'
  post '/login', to: 'users#login'
  delete '/logout', to: 'users#logout'
  get '/clear', to: 'users#clear'

  get '/terms-of-use', to: 'pages#terms'
  get '/about', to: 'pages#about'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews
  validates_uniqueness_of :email
  has_secure_password

  def has_reviewed_document?(document)
    document.reviews.where(user_id: self.id).exists?
  end

  def website
    the_url = super
    if the_url =~ %r{^https?://} || the_url.blank?
      the_url
    else
      "http://#{the_url}"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_action :require_login, only: [:show, :new, :create, :login, :logout, :clear]
  before_action :require_admin, only: [:index, :destroy]
  before_action :require_admin_or_self, only: [:edit, :update]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @requests = Request.order('completed_at DESC').uncompleted
  end

  # GET /users/new
  def new
    redirect_to root_path if logged_in?

    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        cookies.permanent[:email] = @user.email
        format.html { redirect_to documents_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def login
    if request.post?
      @user = User.where("lower(email) = :email", email: params[:email].to_s.downcase).first
      if @user.try(:authenticate, params[:password])
        session[:user_id] = @user.id
        cookies.permanent[:email] = @user.email
        redirect_to return_to_path || documents_path
      else
        flash.now[:error] = "Bad username or password"
      end
    end
  end

  def logout
    reset_session
    redirect_to login_path
  end

  def clear
    reset_session
    cookies.clear
    redirect_to root_path
  end

  private
    def require_admin_or_self
      #raise "!#{require_admin} && #{current_user.id} != #{@user.id} = #{!require_admin && current_user.id != @user.id}"
      return true if current_user.admin? || current_user.id == @user.id
      flash[:error] = "You do not have permission to view that page"
      redirect_to root_path
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :first_name, :last_name, :password, :website, :description, :company_name, :states, :attorney_registration_number)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
= form_for @user, html: { class: "form-horizontal", role: "form" } do |f|
  = render partial: "shared/error_messages", locals: { object: @user }

  %table.table_padded
    - if !logged_in?
      %tr
        %td
        %td
          %em
            Already have an account?
            = link_to 'Login Now', '/login'

    %tr
      %td.cell_collapse= f.label :first_name, class: 'text_capitalize'
      %td= f.text_field :first_name

    %tr
      %td.cell_collapse= f.label :last_name, class: 'text_capitalize'
      %td= f.text_field :last_name

    %tr
      %td.cell_collapse= f.label :email
      %td= f.email_field :email, required: true

    %tr
      %td.cell_collapse= f.label :password
      %td= f.password_field :password, required: f.object.new_record?

    %tr
      %td.cell_collapse= f.label :company_name, 'Employer'
      %td= f.text_field :company_name

    %tr
      %td= f.label :states, "States You Are Licensed"
      %td
        = f.text_field :states, required: true
        .text_small
          %em List every state where you are licensed to practice law

    %tr
      %td.cell_collapse= f.label :attorney_registration_number, class: 'text_capitalize'
      %td= f.text_field :attorney_registration_number, required: true

    %tr
      %td
      %td
        = f.submit 'Sign Up', class: 'btn'

app/views/users/edit.html.haml
/ .float_right
/   = link_to users_path, class: 'btn btn_gray' do
/     %span.fa.fa-fw.fa-arrow-left
/     Back

/   = link_to @user, class: 'btn' do
/     %span.fa.fa-fw.fa-info-circle
/     View

%h1 Edit User

= render 'form'

app/views/users/index.html.haml
%h1 Users

%table.table_index
  %thead
    %tr
      %th Name
      %th Email
      %th{colspan: '2'} Company

  %tbody
    - @users.each do |user|
      %tr
        %td{data: {'col-header': 'Name:'}}= link_to [user.first_name, user.last_name].join(' '), user
        %td{data: {'col-header': 'Email:'}}= user.email
        %td{data: {'col-header': 'Company:'}}= user.company_name
        %td.cell_collapse
          %ul.inline_list
            %li= link_to 'Edit', edit_user_path(user)
            %li= link_to 'Delete', user, data: { confirm: 'Are you sure?' }, method: :delete

app/views/users/login.html.haml
%h1 Attorney Login

= form_tag '/login', action: 'POST', html: {class: "form-horizontal", role: "form"} do |f|

  %table.table_padded
    %tr
      %td.cell_collapse
        %label{for: 'email'} Email
      %td= email_field_tag 'email', cookies[:email]
    %tr
      %td.cell_collapse
        %label{for: 'password'} Password
      %td= password_field_tag 'password', nil
    %tr
      %td
      %td= submit_tag "Login", class: 'btn btn-primary btn-lg btn-block'

app/views/users/new.html.haml
%h1{style: 'margin-bottom:0;'} Sign Up Today

%p.text_xl.text_light.media_xs_text_base_size Start Grading Contracts for the Greater Good

= render 'form'

app/views/users/show.html.haml
.float_right
  - if logged_in?
    - if @user == current_user || current_user.admin?
      = link_to edit_user_path(@user), class: 'btn' do
        %span.fa.fa-fw.fa-pencil
        Edit

    - if @user == current_user
      = link_to logout_path, class: 'btn btn_gray', data: {method: :delete, "no-turbolink" => true} do
        Logout&nbsp;
        %span.fa.fa-fw.fa-sign-out

%h1
  %span.fa.fa-fw.fa-user.text_light
  = [@user.first_name, @user.last_name[0]].join(' ')

%h3 Requests for Contract Reviews

= render partial: 'requests/table', locals:{ requests: @requests }

%h3 Contracts Reviewed by #{@user.first_name}

%table.table_index
  %thead
    %tr
      %th Document Name
      %th Company
      - if logged_in? && (current_user.admin? || (@user.reviews.any? && current_user.id == @user.id))
        %th &nbsp;

  - @user.reviews.each do |review|
    %tr
      %td{data: {'col-header': 'Contract:'}}= link_to review.document.name, review.document
      %td{data: {'col-header': 'Company:'}}= review.document.company_name
      - if logged_in? && (current_user.admin? || current_user.id == review.user_id)
        %td.cell_collapse
          %ul.inline_list
            %li= link_to "Edit Review", edit_review_path(review.id)
            %li= link_to "Delete", review_path(review.id), "data-method" => "delete", "data-confirm" => "Are you sure you want to delete this review? This cannot be undone."