config/routes.rb
Rails.application.routes.draw do
  get 'pages/terms'

  get 'pages/about'

  get 'welcome/index'

  root to: "documents#index"
  resources :bullet_points, except: [:show]
  resources :document_types, except: [:show]
  resources :documents, shallow: true do
    resources :reviews, except: [:show, :index]
    get :find, on: :collection
  end
  resources :users
  resources :requests, except: [:show, :edit, :update]

  get '/login', to: 'users#login'
  post '/login', to: 'users#login'
  delete '/logout', to: 'users#logout'
  get '/clear', to: 'users#clear'

  get '/terms-of-use', to: 'pages#terms'
  get '/about', to: 'pages#about'
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :document_type
  belongs_to :request, optional: true

  has_many :reviewables, through: :document_type
  has_many :reviews, dependent: :destroy

  before_validation :record_parsed_uri, if: :will_save_change_to_url? # url_changed?
  before_create :complete_request
  validate :valid_unique_url

  def self.search(query)
    scope = includes(:document_type, :reviews)

    if query.present?
      scope = scope.where("documents.name ILIKE :query OR documents.company_name ILIKE :query", query: "%#{query}%")
    end

    scope.all.order("company_name DESC")
  end

  # Returns a document by the hostname and path given,
  # If there is no path, maybe the site does it's url
  # exclusively via query params... so search by
  # the host + query instead.
  def self.search_for_url(url)
    uri = URI.parse(url)
    docs = where(uri_host: uri.host.to_s.sub(/^www\./, ""))
    if uri.path.present?
      docs = docs.where(uri_path: uri.path)
    else
      docs = docs.where(uri_path: uri.path, uri_query: uri.query)
    end
    return docs.last
  end

  def summarize_scores
    @summarize_scores = Review.summarize_scores(self)
  end

  def overall_score
    @overall_score ||= begin
      scores = Review.summarize_scores(self).map(&:avg_score)
      return nil if scores.empty?
      scores.sum / scores.size
    end
  end

  private

  # before_validation
  def record_parsed_uri
    return if url.blank?

    self.url = if url.to_s =~ %r{https?://}
      url
    else
      "http://#{url}"
    end

    uri = URI.parse(self.url)
    # Don't save the 'www.' part of the host, so that something like
    # "facebook.com" and "www.facebook.com" will both match,
    # but "apps.facebook.com" will not.
    self.uri_host = uri.host.sub(/^www\./, "")
    self.uri_path = uri.path
    self.uri_query = uri.query
    self.uri_fragment = uri.fragment
  rescue URI::InvalidURIError
    self.uri_host = nil
    self.uri_path = nil
    self.uri_query = nil
    self.uri_fragment = nil
  end

  def valid_unique_url
    if uri_host.blank? || url.blank?
      errors.add(:url, "appears to be invalid")
      return false
    end

    docs = Document
    unless new_record?
      # Exclude self id if this is an update on an
      # existing record.
      docs = docs.where.not(id: self.id)
    end
    docs = docs.search_for_url(self.url)

    if docs.present?
      errors.add(:url, "must be unique")
    end
  end

  def complete_request
    if self.request_id
      self.request.complete
    end
  end
end

app/models/document_type.rb
class DocumentType < ApplicationRecord
  has_many :documents
  has_many :reviewables, dependent: :destroy
  has_many :bullet_points, through: :reviewables

  validates_presence_of :category
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :edit, :update, :destroy]
  skip_before_action :require_login, only: [:index, :show, :find]

  def index
    @documents = Document.search(params[:q])

    render layout: 'welcome'
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
    @summarized_ratings = @document.summarize_scores
  end

  # GET /documents/new
  def new
    @document = Document.new(name: params[:name], url: params[:url], request_id: params[:request_id])

    if current_user.has_reviewed_document?(@document) && !current_user.admin?
      redirect_to document_path(@document), notice: "You have already reviewed that"
    end
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(document_params)

    if current_user.has_reviewed_document?(@document) && !current_user.admin?
      redirect_to document_path(@document), notice: "You have already reviewed that"
    end

    respond_to do |format|
      if @document.save
        format.html { redirect_to new_document_review_path(@document.id), notice: 'Document was successfully created.' }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    respond_to do |format|
      if @document.update_attributes(document_params)
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url, notice: 'Document was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /documents/find.json?document_url=url
  def find
    @document = Document.search_for_url(params[:document_url])
    @review = Review.find_review_for(@document, cookies[:email])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_params
      params.require(:document).permit(
        :name,
        :url,
        :description,
        :version,
        :document_type_id,
        :company_name,
        :auto_accept,
        :notify_on_changes,
        :request_id
      )
    end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_extension.html.haml
.break_small
  = link_to root_url, target: '_blank', class: 'remove_border_bottom' do
    %img.header_logo{src: asset_url('lexlucid-logo-vector.svg')}

- if document
  %h1= document.name

  - if document.reviews.any?
    .overall_stars.js-star-readonly-score{data: {score:  document.overall_score}}

    .break_medium
      .text_small #{number_with_precision(@document.overall_score, precision: 1)} Stars &nbsp; | &nbsp; #{document.reviews.count} Attorney #{"Review".pluralize(@document.reviews.count)}

    %table.text_small.break_small
      - if document.version
        %tr
          %td Version
          %td= document.version

      - document.summarize_scores.each do |rating|
        %tr
          %td #{rating.bullet_point.human_title}
          %td.cell_collapse{style: 'vertical-align:top;'}
            %span.js-star-readonly-score{data: {score: rating.avg_score}}

  - if has_logged_in?
    - if review
      = link_to "Edit Your Review", edit_review_url(review), target: "_blank", class: "btn"
    - else
      = link_to "Review Contract", new_document_review_url(document), target: "_blank", class: "btn"
  - else
    = link_to "View Details", document_url(document), target: "_blank", class: "btn"

- else
  %h1 No Reviews Found

  %p This contract has not been reviewed yet.

  %p
    - if has_logged_in?
      = link_to "Add Contract", new_document_url, target: "_blank", class: "btn js-new-document"
    - else
      = link_to "Request Contract Review", new_request_url, target: "_blank", class: "btn js-new-document"

app/views/documents/_form.html.haml
= form_for @document, html: { class: "form-horizontal", role: "form" } do |f|
  = render partial: "shared/error_messages", locals: { object: @document }

  %table.table_padded
    %tr
      %td.cell_collapse= f.label :name, "Title"
      %td= f.text_field :name

    %tr
      %td.cell_collapse= f.label :company_name, "Company"
      %td= f.text_field :company_name

    %tr
      %td.cell_collapse= f.label :url, "URL"
      %td= f.text_field :url, placeholder: 'http://example.com/terms'

    %tr
      %td.cell_collapse= f.label :document_type_id, "Type", class: "col-sm-2 control-label"
      %td= f.collection_select :document_type_id, DocumentType.order(:category), :id, :category, {}

    %tr
      %td.cell_collapse= f.label :version
      %td= f.text_field :version, placeholder: 'Version Number or Last Updated Date'

    %tr
      %td
      %td
        = f.check_box :auto_accept
        = f.label :auto_accept, "Does the contract attempt to bind users without affirmative acceptance?"

    %tr
      %td
      %td
        = f.check_box :notify_on_changes
        = f.label :notify_on_changes, "Does the company commit to notifying users any time changes are made to the terms of the contract?"

    = f.hidden_field :request_id

    %tr
      %td
      %td
        .break_small
        = f.submit class: 'btn'

        = link_to @document.new_record? ? documents_path : @document, class: 'btn btn_gray' do
          %span.fa.fa-fw.fa-times
          Cancel

app/views/documents/_score.html.haml
.js-lexlucid-panel
  .js-lexlucid-logo LEXLUCID.com
  - if document
    %h1= document.name
    %p
      %table.text_small
        %tr
          %td Score:
          %td
            .js-star-readonly-score{data: {score:  document.overall_score}}
  - else
    %p Document Available For Create

app/views/documents/edit.html.haml
/ .float_right
/   = link_to @document, class: 'btn' do
/     %span.fa.fa-fw.fa-info-circle
/     View

%h1 Edit Contract

= render 'form'

app/views/documents/index.html.haml
- if params[:q].present?
  = link_to documents_path, class: 'btn btn_gray float_right' do
    %span.fa.fa-fw.fa-times
    Clear Search

  %h2#a_doc_results.remove_margin_top Results for: '#{params[:q]}'

- else
  %h2.remove_margin_top Recently Reviewed Contracts

- if @documents.any?
  %table.table_index
    %thead
      %tr
        %th Contract / Agreement
        %th Company
        %th Version / Updated
        %th.text_right Reviews
        %th Grade
        - if logged_in?
          %th

    %tbody
      - i = 0
      - @documents.each do |document|
        - if logged_in? || document.reviews.any?
          %tr
            %td{data: {'col-header': 'Contract:'}}= link_to document.name, document
            %td{data: {'col-header': 'Company:'}}= document.company_name
            %td{data: {'col-header': 'Version:'}}= document.version
            %td.text_right{data: {'col-header': 'Reviews:'}}= document.reviews.count
            %td.cell_collapse{data: {'col-header': 'Grade:'}}
              - if document.reviews.any?
                %span.js-star-readonly-score{data: {size: 'small', score:  document.overall_score}, title: number_with_precision(document.overall_score, precision: 1)}

            - if logged_in?
              %td.cell_collapse
                - if !current_user.has_reviewed_document?(document)
                  = link_to 'Add Review', new_document_review_path( document)

- else
  %p
    %em No Results Were Found

- if params[:q].present?
  .box_gray.text_center
    %h3 Didn't find what you were looking for?

    - if current_user
      %p Add a new contract, then you and other attorneys can review it on LexLucid.

      %p= link_to 'Add Contract', new_document_path(name: params[:q]), class: 'btn'

    - else
      %p You can request a contract to be added and reviewed by attorneys on LexLucid.

      %p= link_to 'Request Contract Review', new_request_path(name: params[:q]), class: 'btn'

app/views/documents/new.html.haml
%h1 New Contract

= render 'form'

app/views/documents/show.html.haml
%h1{style: 'margin-bottom:0.2em'}= @document.name

- if @document.reviews.any?
  %span.js-star-readonly-score{data: {size: 'small', score:  @document.overall_score}, title: @document.overall_score}

  &nbsp;&nbsp;

  %ul.inline_list.text_small.break_medium{style: 'vertical-align:top;'}
    %li #{number_with_precision(@document.overall_score, precision: 1)} Stars
    %li #{@document.reviews.count} Attorney #{"Review".pluralize(@document.reviews.count)}

- if logged_in?
  .break_small
    - if !current_user.has_reviewed_document?(@document)
      = link_to new_document_review_path(@document), class: 'btn' do
        %span.fa.fa-fw.fa-plus
        Add Review

    = link_to edit_document_path(@document), class: 'btn btn_gray' do
      %span.fa.fa-fw.fa-pencil
      Edit Document

%table.table_padded_right.text_small.break_large
  %tr
    %td.cell_collapse.text_right.media_xs_text_right.text_bold Company:
    %td= @document.company_name
  %tr
    %td.cell_collapse.text_right.media_xs_text_right.text_bold URL:
    %td.word_break= link_to @document.url, @document.url, target: "_blank"
  %tr
    %td.cell_collapse.text_right.media_xs_text_right.text_bold Type:
    %td= @document.document_type.category
  %tr
    %td.cell_collapse.text_right.media_xs_text_right.text_bold Version:
    %td= @document.version
  - @summarized_ratings.each do |rating|
    %tr
      %td.cell_collapse.text_right.media_xs_text_right.text_bold= link_to rating.bullet_point.human_title, "#issue-#{rating.bullet_point_id}"
      %td
        .js-star-readonly-score{data: {score: rating.avg_score, size: 'small'}}
  %tr
    %td{colspan: '2'} &nbsp;
  %tr
    - if @document.auto_accept?
      %td.text_right.media_xs_text_right
        %span.fa.fa-fw.fa-lg.fa-exclamation-circle.text_red
      %td
        Warning: You may be bound by the terms of this contract simply by accessing the company&rsquo;s website.
    - else
      %td.text_right.media_xs_text_right
        %span.fa.fa-fw.fa-lg.fa-check-square-o.text_green
      %td
        You are NOT bound by the terms of this contract simply by accessing the company&rsquo;s website.
  %tr
    - if @document.notify_on_changes?
      %td.text_right.media_xs_text_right
        %span.fa.fa-fw.fa-lg.fa-check-square-o.text_green
      %td The company has committed to notifying users any time changes are made to the terms of the contract.

    - else
      %td.text_right.media_xs_text_right
        %span.fa.fa-fw.fa-lg.fa-exclamation-circle.text_red
      %td Warning: The company has NOT committed to notifying users any time changes are made to the terms of the contract.

- @summarized_ratings.each do |rating|
  .box.media_xs_bleed.break_medium{id: "issue-#{rating.bullet_point_id}"}
    %h3= rating.bullet_point.human_title

    = simple_format rating.bullet_point.human_description

    .break_small
      %span.js-star-readonly-score{data: {score: rating.avg_score, size: 'small'}}

      %span.text_small{style: 'vertical-align:top;'} &nbsp; #{pluralize(rating.reviews_done, "Review")}

    %div{class: "js-review-bullet-#{rating.bullet_point_id}"}
      %table.table_index
        %thead
          %tr
            %th Attorney
            %th Grade
            %th Explanation
        %tbody
          - rating.bullet_point.ratings.for_document(@document).preload(:review => :user).each do |lawyer_rating|
            %tr
              %td.cell_collapse{data: {'col-header': 'Attorney:'}}= link_to "#{lawyer_rating.review.user.first_name} #{lawyer_rating.review.user.last_name[0]}", lawyer_rating.review.user
              %td.cell_collapse{data: {'col-header': 'Grade:'}}
                %span.js-star-readonly-score{data: {size: 'small', score:  lawyer_rating.score}, title: lawyer_rating.score}
              %td{data: {'col-header': 'Desc:'}}= simple_format lawyer_rating.description