config/routes.rb
Rails.application.routes.draw do
  get 'pages/terms'

  get 'pages/about'

  get 'welcome/index'

  root to: "documents#index"
  resources :bullet_points, except: [:show]
  resources :document_types, except: [:show]
  resources :documents, shallow: true do
    resources :reviews, except: [:show, :index]
    get :find, on: :collection
  end
  resources :users
  resources :requests, except: [:show, :edit, :update]

  get '/login', to: 'users#login'
  post '/login', to: 'users#login'
  delete '/logout', to: 'users#logout'
  get '/clear', to: 'users#clear'

  get '/terms-of-use', to: 'pages#terms'
  get '/about', to: 'pages#about'
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :require_admin_or_self, only: [:edit, :update, :destroy]

  # GET /reviews/1
  # GET /reviews/1.json
  def show
    redirect_to document_path(@review.document.id)
  end

  # GET /reviews/new
  def new
    @document = Document.find(params[:document_id])

    if current_user.has_reviewed_document?(@document)
      redirect_to @document, notice: "You have already reviewed this document. You can go to your profile to update the review if you wish."
      return
    end

    @review = @document.reviews.build

    build_review_children
  end

  # GET /reviews/1/edit
  def edit
    @document = @review.document
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @document = Document.find(params[:document_id])

    if current_user.has_reviewed_document?(@document)
      redirect_to @document, notice: "You have already reviewed this document. You can go to your profile to update the review if you wish."
      return
    end

    @review = @document.reviews.build(review_params)
    @review.user = current_user

    respond_to do |format|
      if @review.save
        format.html { redirect_to @document, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to user_path(@review.user_id), notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html {
          @document = @review.document
          render :edit
        }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to user_path(@review.user_id), notice: 'Review was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    def require_admin_or_self
      return true if current_user.admin? || current_user.id == @review.user_id
      flash[:error] = "You do not have permission to view that page"
      redirect_to root_path
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    def build_review_children
      @document.reviewables.order(:position).each do |reviewable|
        @review.ratings.build(bullet_point: reviewable.bullet_point)
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(
        :lawyer_id,
        :attorney_not_affiliated,
        ratings_attributes: [
          :id,
          :score,
          :bullet_point_id,
          :description
        ]
      )
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.haml
= render partial: "shared/error_messages", locals: { object: @review }

.box_gray
  .fa.fa-3x.fa-exclamation-circle.text_light{style: 'float:left;margin-right:0.3em;'}

  %div{style: 'max-width:55em;'}
    = f.check_box :attorney_not_affiliated

    = f.label :attorney_not_affiliated, "Check this box to confirm that there are no circumstances specific to this company that might preclude you from giving a fair and impartial review of this contract."

= f.fields_for :ratings do |rating_form|
  %hr

  .panel.panel-default
    %table.table_padded.panel-body
      %tr.form-group
        %td.cell_collapse= rating_form.label :bullet_point_id, "Issue", class: "col-sm-2 control-label"
        %td.col-sm-10
          = rating_form.object.bullet_point.human_title

      %tr.form-group
        %td.cell_collapse= rating_form.label :score, 'Grade', class: 'col-sm-2 control-label'
        %td.col-sm-10
          .js-star-score
          = rating_form.hidden_field :score, class: "js-input-score"

      %tr.form-group
        %td.cell_collapse= rating_form.label :description, class: 'col-sm-2 control-label'
        %td.col-sm-10
          = rating_form.text_area :description, class: 'form-control'

app/views/reviews/edit.html.haml
%h1
  %span.text_light Edit Review:
  #{@document.name}

%table.table_padded_right.text_small.break_large
  %tr
    %td.cell_collapse.text_right.media_xs_text_right.text_bold Company:
    %td= @document.company_name
  %tr
    %td.cell_collapse.text_right.media_xs_text_right.text_bold URL:
    %td.word_break= link_to @document.url, @document.url, target: "_blank"
  %tr
    %td.cell_collapse.text_right.media_xs_text_right.text_bold Type:
    %td= @document.document_type.category
  %tr
    %td.cell_collapse.text_right.media_xs_text_right.text_bold Description:
    %td= @document.description
  %tr
    %td.cell_collapse.text_right.media_xs_text_right.text_bold Version:
    %td= @document.version

= form_for @review, html: { class: "form-horizontal", role: "form" } do |f|
  = render partial: 'form', locals: {f: f}

  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit "Update Review", class: 'btn'

      = link_to user_path(@review.user_id), class: 'btn btn_gray' do
        %span.fa.fa-fw.fa-times
        Cancel

app/views/reviews/index.html.haml
.page-header
  = link_to new_review_path, class: 'btn btn-primary' do
    %span.fa.fa-fw.fa-plus
    New Review
  %h1 Listing Reviews

.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th Attorney
        %th Body
        %th
        %th
        %th

    %tbody
      - @reviews.each do |review|
        %tr
          %td= review.lawyer
          %td= review.body
          %td= link_to 'Show', review
          %td= link_to 'Edit', edit_review_path(review)
          %td= link_to 'Delete', review, data: { confirm: 'Are you sure?' }, method: :delete

app/views/reviews/new.html.haml
%h1
  %span.text_light New Review:
  #{@document.name}

%table.table_padded_right.text_small.break_large
  %tr
    %td.cell_collapse.text_right.media_xs_text_right.text_bold Company:
    %td= @document.company_name
  %tr
    %td.cell_collapse.text_right.media_xs_text_right.text_bold URL:
    %td.word_break= link_to @document.url, @document.url, target: "_blank"
  %tr
    %td.cell_collapse.text_right.media_xs_text_right.text_bold Type:
    %td= @document.document_type.category
  %tr
    %td.cell_collapse.text_right.media_xs_text_right.text_bold Description:
    %td= @document.description
  %tr
    %td.cell_collapse.text_right.media_xs_text_right.text_bold Version:
    %td= @document.version

= form_for [@document, @review], html: { class: "form-horizontal", role: "form" } do |f|
  = render partial: 'form', locals: {f: f}

  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit "Add Review", class: 'btn'

      = link_to documents_path, class: 'btn btn_gray' do
        %span.fa.fa-fw.fa-times
        Cancel