config/routes.rb
Rails.application.routes.draw do
  get 'pages/terms'

  get 'pages/about'

  get 'welcome/index'

  root to: "documents#index"
  resources :bullet_points, except: [:show]
  resources :document_types, except: [:show]
  resources :documents, shallow: true do
    resources :reviews, except: [:show, :index]
    get :find, on: :collection
  end
  resources :users
  resources :requests, except: [:show, :edit, :update]

  get '/login', to: 'users#login'
  post '/login', to: 'users#login'
  delete '/logout', to: 'users#logout'
  get '/clear', to: 'users#clear'

  get '/terms-of-use', to: 'pages#terms'
  get '/about', to: 'pages#about'
end

app/views/layouts/_footer.html.haml
%footer.footer.text_light
  .content_width.text_small
    .cols.break_xl
      .col_40
        %table.break_small
          %tr
            %td{style: 'vertical-align:middle;padding-right:1em;'}
              %a{href: 'https://legaltalknetwork.com/global-legal-hackathon-denver/'}
                %img{src: asset_path('glh-denver-winners.svg'), style: 'width:12.5em;opacity:0.417;'}
            %td{style: 'vertical-align:middle;padding-left:1em;'}
              %a{href: 'https://globallegalhackathon.com/glh2018-finals/'}
                %img{src: asset_path('glh-winners-logo.svg'), style: 'width:17.5em;opacity:0.417;'}

      .col_60
        .cols
          .col_30.break_small.border_left
            %h4.text_bold.break_small.text_uppercase LexLucid

            %ul.remove_bullets.media_xs_cols_flow_two
              %li= link_to 'Home', root_path

              - if logged_in?
                %li= link_to 'Dashboard', current_user
                %li= link_to "Add Contract", new_document_path

                - if current_user.admin?
                  %li= link_to 'Document Types', document_types_path
                  %li= link_to 'Issues', bullet_points_path
                  %li= link_to 'Users', users_path

              %li= link_to 'About', about_path

              - if !logged_in? && !has_logged_in?
                %li= link_to 'Request Review', new_request_path
                %li= link_to 'Attorney Registration', new_user_path

              - if has_logged_in? && !logged_in?
                %li= link_to 'Attorney Login', '/login'

          .col_40.break_small.border_left
            %h4.text_bold.break_small.text_uppercase Chrome Extension

            %p Get access to one-click reviews with our new extension for Chrome.

            %p
              = link_to 'https://chrome.google.com/webstore/detail/lexlucid/cfcdiophfjnmjnelkmgdkeejfabenhpo', class: 'btn btn_gray' do
                %span.text_light.text_bold
                  Get Extension &nbsp;
                  %span.fa.fa-lg.fa-chevron-circle-right

          .col_30.break_small.border_left
            %h4.text_bold.break_small.text_uppercase Follow Us

            %ul.remove_bullets.text_large.media_xs_cols_flow_two
              %li
                = link_to 'https://twitter.com/LexLucid', class: 'remove_border_bottom' do
                  %span.fa.fa-lg.fa-twitter-square
                  Twitter
              %li
                = link_to 'https://www.facebook.com/lexlucidapp', class: 'remove_border_bottom' do
                  %span.fa.fa-lg.fa-facebook-square
                  Facebook

    %p
      &copy;
      = Time.now.year
      LexLucid. <br class='media_xs_show'>All rights reserved.

      = link_to 'Terms of Use', terms_of_use_path

    .cols_flow_three
      %p.text_small LexLucid is in beta and attorney credentials have not been independently verified by us. The reviews reflected here are the opinions of the individuals providing those reviews only, and have not been thoroughly checked for quality control. If you have any issues with any reviews, please <a href='https://twitter.com/LexLucid'>contact us</a>. LexLucid is not a law firm and does not provide legal advice. The reviews provided here are based on general fairness to all consumers, without considering any individual facts. Your facts may vary.  If you wish to understand how a contract applies to you specifically, you should seek independent legal counsel.

app/views/layouts/_google_analytics.html.erb
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-114760529-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-114760529-1');
</script>

app/views/layouts/_head.html.haml
%meta{charset: "utf-8"}
%meta{content: "IE=edge", "http-equiv" => "X-UA-Compatible"}
%meta{content: "width=device-width, initial-scale=1", name: "viewport"}
%meta{content: "", name: "description"}
%meta{content: "", name: "author"}
%title LexLucid

<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/site.webmanifest">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="theme-color" content="#ffffff">

/ HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
/[if lt IE 9]
  = javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js"

= stylesheet_link_tag 'application', media: 'all'
= javascript_include_tag 'application'
= csrf_meta_tags

app/views/layouts/_navbar.html.haml
- if logged_in?
  = link_to current_user, class: active_page?("users#show") && current_user.id == @user.id ? 'active' : '' do
    Dashboard

  = link_to new_document_path, class: active_page?("documents#new", "documents#create") ? 'active' : '' do
    Add Contract

= link_to about_path, class: active_page?("pages#about") ? 'active' : '' do
  About

- if !logged_in? && !has_logged_in?
  = link_to new_user_path, class: active_page?("users") ? 'active' : '' do
    Attorney Registration

- if has_logged_in? && !logged_in?
  = link_to '/login', class: active_page?("users") ? 'active' : '' do
    Attorney Login

app/views/layouts/_navbar_admin.html.haml
- if logged_in?
  - if current_user.admin?
    .admin_navbar.bg_black.text_white.text_small
      .content_width{style: 'overflow:hidden;'}
        .float_left
          %a{href: '#', data: {toggle: '.js_admin_navbar_toggle'}}
            %span.fa.fa-sliders
            &nbsp; ADMIN

        .float_right.js_admin_navbar_toggle
          = link_to 'Document Types', document_types_path, class: active_page?("document_types") ? 'active' : ''
          = link_to 'Issues', bullet_points_path, class: active_page?("bullet_points") ? 'active' : ''
          = link_to 'Users', users_path, class: active_page?("users#index") ? 'active' : ''
          = link_to 'Logout', logout_path, data: {method: :delete, "no-turbolink" => true}

app/views/layouts/application.html.haml
!!!
%html
  %head
    = render partial: 'layouts/google_analytics'
    = render partial: 'layouts/head'

  %body
    = render partial: 'layouts/navbar_admin'

    %header.app_header
      .content_width
        %table
          %tr
            %td
              %a{href: '/'}
                %img.app_header_logo{src: asset_path('lexlucid-logo-vector.svg')}

            %td.media_xs_text_right{style: 'vertical-align:middle;'}
              %a.header_mobile_nav_button{href: '#', data: {toggle: '.js_header_mobile_nav_button'}}
                %span.fa.fa-fw.fa-bars

        %nav.header_nav.js_header_mobile_nav_button
          = render partial: 'layouts/navbar'

    - if current_page?('/about')
      = yield

    - else
      .app_content
        .content_width
          - flash.each do |name, msg|
            %div{class: "alert alert-#{name.to_sym == :error ? 'danger' : 'success'} alert-dismissable", role: "alert"}
              %button.close{type: "button", data: {dismiss: "alert"} }
                %span{aria: {hidden: "true"} } &times;
                %span.sr-only Close
              = msg

          - if request.path.include?('/documents') && !request.path.include?('/new') && !request.path.include?('/edit')

            .cols.cols_padding_large
              .col_75
                = yield

              .col_25
                .box_gray.break_medium.bg_purple.text_small.text_white
                  %h4
                    %span.fa.fa-hand-pointer-o
                    One-Click Reviews

                  %p The LexLucid Chrome extension puts you one-click away from seeing reviews or adding new ones, without leaving the site you&rsquo;re browsing.

                  = link_to 'https://chrome.google.com/webstore/detail/lexlucid/cfcdiophfjnmjnelkmgdkeejfabenhpo', class: 'btn btn_yellow' do
                    Get Extension &nbsp;
                    %span.fa.fa-chevron-circle-right

                - if !logged_in? && !has_logged_in?
                  .box_gray.break_medium.text_small
                    %h4
                      %span.fa.fa-institution
                      Attorneys

                    %p Help consumers stay safe and make better informed decisions by registering and grading contracts on LexLucid.

                    = link_to 'Register Today', new_user_path, class: 'btn'

                .box.break_medium.text_small
                  %h4 Follow LexLucid

                  %ul.remove_bullets.media_xs_cols_flow_two
                    %li
                      = link_to 'https://twitter.com/LexLucid', class: 'remove_border_bottom' do
                        %span.fa.fa-lg.fa-twitter-square
                        Twitter
                    %li
                      = link_to 'https://www.facebook.com/lexlucidapp', class: 'remove_border_bottom' do
                        %span.fa.fa-lg.fa-facebook-square
                        Facebook

          - else
            = yield

    = render partial: 'layouts/footer'

app/views/layouts/welcome.html.haml
!!!
%html
  %head
    = render partial: 'layouts/google_analytics'
    = render partial: 'layouts/head'

  %body
    = render partial: 'layouts/navbar_admin'

    %header.app_header
      .content_width
        %table
          %tr
            %td
              %a.media_xs_show{href: '/'}
                %img.app_header_logo{src: asset_path('lexlucid-logo-vector.svg')}

            %td.media_xs_text_right{style: 'vertical-align:middle;'}
              %a.header_mobile_nav_button{href: '#', data: {toggle: '.js_header_mobile_nav_button'}}
                %span.fa.fa-fw.fa-bars

        %nav.header_nav.media_xs_break_small.js_header_mobile_nav_button
          = render partial: 'layouts/navbar'

    .home_header.media_xs_text_center
      .content_width
        .break_xs
          %a.media_xs_hide{href: '/'}
            %img.home_logo{src: asset_path('lexlucid-logo-vector.svg')}

        .home_header_indent
          .break_large.media_xs_break_small
            %h1.remove_margin_top Grading contracts for the greater&nbsp;good.

          .home_header_search{style: 'overflow:hidden;'}
            = form_tag documents_path, method: :get do
              = text_field_tag :q, params[:q], id: 'home_header_input', placeholder: 'Find a Company'
              = submit_tag "Go", id: 'home_header_submit'

    .app_content
      .content_width
        - flash.each do |name, msg|
          %div{class: "alert alert-#{name.to_sym == :error ? 'danger' : 'success'} alert-dismissable", role: "alert"}
            %button.close{type: "button", data: {dismiss: "alert"} }
              %span{aria: {hidden: "true"} } &times;
              %span.sr-only Close
            = msg
        = yield

    .row_padding_large.bg_gray.home_whatis
      .home_whatis_bg
      .content_width.text_large.media_xs_text_base_size
        .cols
          .col_60
            %h2.remove_margin_top What Is LexLucid?

            .cols_flow_two0
              %p We&rsquo;re all guilty of checking the box online, and signing an agreement to terms we haven&rsquo;t read or don&rsquo;t understand.

              %p LexLucid is the solution. Certified attorneys grade and review legal contracts, so you can quickly see what you&rsquo;re getting into the next time you agree to the terms. Our reviews put things in plain English, so you can feel confident agreeing to the terms.

              = link_to about_path, class: 'btn' do
                About LexLucid &nbsp;
                %span.fa.fa-chevron-circle-right

    .row_padding_large.bg_darker_20
      .content_width.text_large.media_xs_text_base_size
        .cols
          .col_33.media_xs_hide
            %a{href: 'https://legaltalknetwork.com/podcasts/special-reports/2018/03/celebrating-the-denver-winners-of-the-global-legal-hackathon/'}
              %img{src: asset_path('glh-denver-pod-album.jpg')}

          .col_66
            .media_xs_cols.media_xs_break_small
              .media_xs_col_33.media_xs_show
                %a{href: 'https://legaltalknetwork.com/podcasts/special-reports/2018/03/celebrating-the-denver-winners-of-the-global-legal-hackathon/'}
                  %img{src: asset_path('glh-denver-pod-album.jpg')}

              .media_xs_col_66
                .media_xs_show.break_small

                .text_uppercase
                  %span.fa.fa-microphone
                  &nbsp;Featured on Legal Talk Network

            %h2.remove_margin_top= link_to 'Celebrating the Denver Winners of the Global Legal Hackathon', 'https://legaltalknetwork.com/podcasts/special-reports/2018/03/celebrating-the-denver-winners-of-the-global-legal-hackathon/', class: 'remove_border_bottom'

            %p.break_medium.media_xs_break_small Listen to the LexLucid team talk about their experience at the Global Legal Hackathon in Denver, Colorado, where they took first place for their project inspired by one of Hadfield&rsquo;s challenges.

            <audio style='width:100%;' controls="" preload="none">
            <source src="https://traffic.libsyn.com/sr/episode_429.mp3">
            <p>Your user agent does not support the HTML5 Audio element.</p>
            </audio>

    .row_padding_large.bg_purple.text_white
      .content_width
        .cols.cols_padding_large.text_large.media_xs_text_base_size
          .col_60.media_xs_break_small
            .break_medium.media_xs_hide
            %h2{style: 'margin:0;'}
              %span.fa.fa-hand-pointer-o
              One-Click Reviews

            %p.text_uppercase with the LexLucid Chrome extension

            %p Just one-click to see attorney contract reviews from LexLucid, without having to leave the site you&rsquo;re browsing.

            %p Consumers can request reviews for new  contracts, while attorneys can add new contracts or review existing ones.

            %p
              = link_to 'https://chrome.google.com/webstore/detail/lexlucid/cfcdiophfjnmjnelkmgdkeejfabenhpo', class: 'btn btn_yellow' do
                Get Chrome Extension &nbsp;
                %span.fa.fa-chevron-circle-right

          .col_40
            %a{href: 'https://chrome.google.com/webstore/detail/lexlucid/cfcdiophfjnmjnelkmgdkeejfabenhpo'}
              %img{src: asset_path('lexlucid-chrome-ext-2.gif')}

    - if !logged_in? && !has_logged_in?
      .row.bg_darker_20
        .content_width.text_large.media_xs_text_base_size.text_center{style: 'max-width:38em;'}
          %h2.remove_margin_top Are You an Attorney?

          %p Help consumers stay safe and make better informed decisions by registering and grading contracts on LexLucid.

          = link_to new_user_path, class: 'btn' do
            Register Today &nbsp;
            %span.fa.fa-sign-in


    = render partial: 'layouts/footer'